# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResActor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResActor.proto',
  package='',
  serialized_pb=_b('\n\x0eResActor.proto\"\x8e\x01\n\x08ResActor\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x0c\n\x04type\x18\x03 \x02(\x05\x12\r\n\x05level\x18\x04 \x02(\x05\x12\x0e\n\x06prefab\x18\x05 \x02(\t\x12\x0e\n\x06radius\x18\x06 \x02(\x02\x12\x0e\n\x06skills\x18\x07 \x03(\x05\x12\r\n\x05items\x18\x08 \x03(\x05\x12\r\n\x05speed\x18\t \x02(\x02\x12\x0b\n\x03\x65xp\x18\n \x02(\x05\"*\n\x0eResActor_ARRAY\x12\x18\n\x05items\x18\x01 \x03(\x0b\x32\t.ResActor')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESACTOR = _descriptor.Descriptor(
  name='ResActor',
  full_name='ResActor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ResActor.id', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ResActor.type', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='ResActor.level', index=2,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prefab', full_name='ResActor.prefab', index=3,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='radius', full_name='ResActor.radius', index=4,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skills', full_name='ResActor.skills', index=5,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='ResActor.items', index=6,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ResActor.speed', index=7,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp', full_name='ResActor.exp', index=8,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=161,
)


_RESACTOR_ARRAY = _descriptor.Descriptor(
  name='ResActor_ARRAY',
  full_name='ResActor_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ResActor_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=205,
)

_RESACTOR_ARRAY.fields_by_name['items'].message_type = _RESACTOR
DESCRIPTOR.message_types_by_name['ResActor'] = _RESACTOR
DESCRIPTOR.message_types_by_name['ResActor_ARRAY'] = _RESACTOR_ARRAY

ResActor = _reflection.GeneratedProtocolMessageType('ResActor', (_message.Message,), dict(
  DESCRIPTOR = _RESACTOR,
  __module__ = 'ResActor_pb2'
  # @@protoc_insertion_point(class_scope:ResActor)
  ))
_sym_db.RegisterMessage(ResActor)

ResActor_ARRAY = _reflection.GeneratedProtocolMessageType('ResActor_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _RESACTOR_ARRAY,
  __module__ = 'ResActor_pb2'
  # @@protoc_insertion_point(class_scope:ResActor_ARRAY)
  ))
_sym_db.RegisterMessage(ResActor_ARRAY)


# @@protoc_insertion_point(module_scope)
