# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResExp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResExp.proto',
  package='',
  serialized_pb=_b('\n\x0cResExp.proto\"b\n\x06ResExp\x12\r\n\x05level\x18\x02 \x02(\x05\x12\x0b\n\x03min\x18\x03 \x02(\x05\x12\x0b\n\x03max\x18\x04 \x02(\x05\x12\x0e\n\x06hp_lmt\x18\x05 \x02(\x05\x12\x0e\n\x06\x61ttack\x18\x06 \x02(\x05\x12\x0f\n\x07\x64\x65\x66\x65nce\x18\x07 \x02(\x05\"&\n\x0cResExp_ARRAY\x12\x16\n\x05items\x18\x01 \x03(\x0b\x32\x07.ResExp')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESEXP = _descriptor.Descriptor(
  name='ResExp',
  full_name='ResExp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='ResExp.level', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='ResExp.min', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='ResExp.max', index=2,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp_lmt', full_name='ResExp.hp_lmt', index=3,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack', full_name='ResExp.attack', index=4,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='defence', full_name='ResExp.defence', index=5,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=114,
)


_RESEXP_ARRAY = _descriptor.Descriptor(
  name='ResExp_ARRAY',
  full_name='ResExp_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ResExp_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=154,
)

_RESEXP_ARRAY.fields_by_name['items'].message_type = _RESEXP
DESCRIPTOR.message_types_by_name['ResExp'] = _RESEXP
DESCRIPTOR.message_types_by_name['ResExp_ARRAY'] = _RESEXP_ARRAY

ResExp = _reflection.GeneratedProtocolMessageType('ResExp', (_message.Message,), dict(
  DESCRIPTOR = _RESEXP,
  __module__ = 'ResExp_pb2'
  # @@protoc_insertion_point(class_scope:ResExp)
  ))
_sym_db.RegisterMessage(ResExp)

ResExp_ARRAY = _reflection.GeneratedProtocolMessageType('ResExp_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _RESEXP_ARRAY,
  __module__ = 'ResExp_pb2'
  # @@protoc_insertion_point(class_scope:ResExp_ARRAY)
  ))
_sym_db.RegisterMessage(ResExp_ARRAY)


# @@protoc_insertion_point(module_scope)
