# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResSkill.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResSkill.proto',
  package='',
  serialized_pb=_b('\n\x0eResSkill.proto\"\xe8\x02\n\x08ResSkill\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x0c\n\x04type\x18\x03 \x02(\x05\x12\r\n\x05level\x18\x04 \x02(\x05\x12\n\n\x02hp\x18\x05 \x02(\x05\x12\x17\n\x0f\x61ttack_duration\x18\x06 \x02(\x05\x12\x0e\n\x06\x62ullet\x18\x07 \x02(\x05\x12\x0c\n\x04\x66ood\x18\x08 \x02(\x05\x12\x0e\n\x06hp_lmt\x18\t \x02(\x05\x12\x11\n\tsub_speed\x18\n \x02(\x02\x12\x0e\n\x06\x61ttack\x18\x0b \x02(\x05\x12\x0f\n\x07\x64\x65\x66\x65nce\x18\x0c \x02(\x05\x12\x13\n\x0b\x61ttack_dist\x18\r \x02(\x02\x12\x11\n\tfind_dist\x18\x0e \x02(\x02\x12\x11\n\tlose_dist\x18\x0f \x02(\x02\x12\x11\n\tmax_count\x18\x10 \x02(\x05\x12\x0c\n\x04kind\x18\x11 \x02(\x05\x12\x11\n\thit_ratio\x18\x12 \x02(\x05\x12\x13\n\x0b\x64odge_ratio\x18\x13 \x02(\x05\x12\x12\n\ncrit_ratio\x18\x14 \x02(\x05\x12\x14\n\x0c\x64\x65\x63rit_ratio\x18\x15 \x02(\x05\"*\n\x0eResSkill_ARRAY\x12\x18\n\x05items\x18\x01 \x03(\x0b\x32\t.ResSkill')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESSKILL = _descriptor.Descriptor(
  name='ResSkill',
  full_name='ResSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ResSkill.id', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ResSkill.type', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='ResSkill.level', index=2,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='ResSkill.hp', index=3,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_duration', full_name='ResSkill.attack_duration', index=4,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bullet', full_name='ResSkill.bullet', index=5,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='food', full_name='ResSkill.food', index=6,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp_lmt', full_name='ResSkill.hp_lmt', index=7,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_speed', full_name='ResSkill.sub_speed', index=8,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack', full_name='ResSkill.attack', index=9,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='defence', full_name='ResSkill.defence', index=10,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_dist', full_name='ResSkill.attack_dist', index=11,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='find_dist', full_name='ResSkill.find_dist', index=12,
      number=14, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lose_dist', full_name='ResSkill.lose_dist', index=13,
      number=15, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_count', full_name='ResSkill.max_count', index=14,
      number=16, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='ResSkill.kind', index=15,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hit_ratio', full_name='ResSkill.hit_ratio', index=16,
      number=18, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dodge_ratio', full_name='ResSkill.dodge_ratio', index=17,
      number=19, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crit_ratio', full_name='ResSkill.crit_ratio', index=18,
      number=20, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='decrit_ratio', full_name='ResSkill.decrit_ratio', index=19,
      number=21, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=379,
)


_RESSKILL_ARRAY = _descriptor.Descriptor(
  name='ResSkill_ARRAY',
  full_name='ResSkill_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ResSkill_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=423,
)

_RESSKILL_ARRAY.fields_by_name['items'].message_type = _RESSKILL
DESCRIPTOR.message_types_by_name['ResSkill'] = _RESSKILL
DESCRIPTOR.message_types_by_name['ResSkill_ARRAY'] = _RESSKILL_ARRAY

ResSkill = _reflection.GeneratedProtocolMessageType('ResSkill', (_message.Message,), dict(
  DESCRIPTOR = _RESSKILL,
  __module__ = 'ResSkill_pb2'
  # @@protoc_insertion_point(class_scope:ResSkill)
  ))
_sym_db.RegisterMessage(ResSkill)

ResSkill_ARRAY = _reflection.GeneratedProtocolMessageType('ResSkill_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _RESSKILL_ARRAY,
  __module__ = 'ResSkill_pb2'
  # @@protoc_insertion_point(class_scope:ResSkill_ARRAY)
  ))
_sym_db.RegisterMessage(ResSkill_ARRAY)


# @@protoc_insertion_point(module_scope)
