//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResExp.proto
namespace GameData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResExp")]
  public partial class ResExp : global::ProtoBuf.IExtensible
  {
    public ResExp() {}
    
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _min;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"min", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int min
    {
      get { return _min; }
      set { _min = value; }
    }
    private int _max;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max
    {
      get { return _max; }
      set { _max = value; }
    }
    private int _hp_lmt;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp_lmt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp_lmt
    {
      get { return _hp_lmt; }
      set { _hp_lmt = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _defence;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResExp_ARRAY")]
  public partial class ResExp_ARRAY : global::ProtoBuf.IExtensible
  {
    public ResExp_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<ResExp> _items = new global::System.Collections.Generic.List<ResExp>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResExp> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}