//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResScene.proto
namespace GameData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResScene")]
  public partial class ResScene : global::ProtoBuf.IExtensible
  {
    public ResScene() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _actor_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"actor_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actor_id
    {
      get { return _actor_id; }
      set { _actor_id = value; }
    }
    private int _pos_x;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_z;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private string _range;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"range", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string range
    {
      get { return _range; }
      set { _range = value; }
    }
    private float _reset_time;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"reset_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float reset_time
    {
      get { return _reset_time; }
      set { _reset_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResScene_ARRAY")]
  public partial class ResScene_ARRAY : global::ProtoBuf.IExtensible
  {
    public ResScene_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<ResScene> _items = new global::System.Collections.Generic.List<ResScene>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResScene> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}