//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResSkill.proto
namespace GameData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSkill")]
  public partial class ResSkill : global::ProtoBuf.IExtensible
  {
    public ResSkill() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _attack_duration;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"attack_duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack_duration
    {
      get { return _attack_duration; }
      set { _attack_duration = value; }
    }
    private int _bullet;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"bullet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bullet
    {
      get { return _bullet; }
      set { _bullet = value; }
    }
    private int _food;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"food", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int food
    {
      get { return _food; }
      set { _food = value; }
    }
    private int _hp_lmt;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"hp_lmt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp_lmt
    {
      get { return _hp_lmt; }
      set { _hp_lmt = value; }
    }
    private float _sub_speed;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"sub_speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float sub_speed
    {
      get { return _sub_speed; }
      set { _sub_speed = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _defence;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private float _attack_dist;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"attack_dist", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attack_dist
    {
      get { return _attack_dist; }
      set { _attack_dist = value; }
    }
    private float _find_dist;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"find_dist", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float find_dist
    {
      get { return _find_dist; }
      set { _find_dist = value; }
    }
    private float _lose_dist;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"lose_dist", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float lose_dist
    {
      get { return _lose_dist; }
      set { _lose_dist = value; }
    }
    private int _max_count;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"max_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_count
    {
      get { return _max_count; }
      set { _max_count = value; }
    }
    private int _kind;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"kind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int kind
    {
      get { return _kind; }
      set { _kind = value; }
    }
    private int _hit_ratio;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"hit_ratio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hit_ratio
    {
      get { return _hit_ratio; }
      set { _hit_ratio = value; }
    }
    private int _dodge_ratio;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"dodge_ratio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dodge_ratio
    {
      get { return _dodge_ratio; }
      set { _dodge_ratio = value; }
    }
    private int _crit_ratio;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"crit_ratio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int crit_ratio
    {
      get { return _crit_ratio; }
      set { _crit_ratio = value; }
    }
    private int _decrit_ratio;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"decrit_ratio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int decrit_ratio
    {
      get { return _decrit_ratio; }
      set { _decrit_ratio = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSkill_ARRAY")]
  public partial class ResSkill_ARRAY : global::ProtoBuf.IExtensible
  {
    public ResSkill_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<ResSkill> _items = new global::System.Collections.Generic.List<ResSkill>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResSkill> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}