# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MultiCopy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MultiCopy.proto',
  package='',
  serialized_pb=_b('\n\x0fMultiCopy.proto\")\n\tMultiCopy\x12\x0b\n\x03key\x18\x02 \x02(\t\x12\x0f\n\x05value\x18\x03 \x01(\t:\x00\",\n\x0fMultiCopy_ARRAY\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.MultiCopy')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MULTICOPY = _descriptor.Descriptor(
  name='MultiCopy',
  full_name='MultiCopy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MultiCopy.key', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='MultiCopy.value', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=60,
)


_MULTICOPY_ARRAY = _descriptor.Descriptor(
  name='MultiCopy_ARRAY',
  full_name='MultiCopy_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='MultiCopy_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=106,
)

_MULTICOPY_ARRAY.fields_by_name['items'].message_type = _MULTICOPY
DESCRIPTOR.message_types_by_name['MultiCopy'] = _MULTICOPY
DESCRIPTOR.message_types_by_name['MultiCopy_ARRAY'] = _MULTICOPY_ARRAY

MultiCopy = _reflection.GeneratedProtocolMessageType('MultiCopy', (_message.Message,), dict(
  DESCRIPTOR = _MULTICOPY,
  __module__ = 'MultiCopy_pb2'
  # @@protoc_insertion_point(class_scope:MultiCopy)
  ))
_sym_db.RegisterMessage(MultiCopy)

MultiCopy_ARRAY = _reflection.GeneratedProtocolMessageType('MultiCopy_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _MULTICOPY_ARRAY,
  __module__ = 'MultiCopy_pb2'
  # @@protoc_insertion_point(class_scope:MultiCopy_ARRAY)
  ))
_sym_db.RegisterMessage(MultiCopy_ARRAY)


# @@protoc_insertion_point(module_scope)
